<!doctype html>
<html lang="id">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{$documentNumber|escape}</title>
	<style>
		:root {ldelim} --jp-accent: {$accentColor|escape}; {rdelim}
		{literal}
		body{margin:0;background:#edf1f0;color:#182421;font:16px/1.65 Georgia,serif}.actions{text-align:center;margin:18px}.actions button{border:0;border-radius:8px;background:var(--jp-accent);color:#fff;padding:11px 20px;font:bold 14px Arial;cursor:pointer}.sheet{box-sizing:border-box;width:210mm;min-height:297mm;margin:20px auto;padding:18mm 20mm 20mm;background:#fff;border:10px double var(--jp-accent);box-shadow:0 12px 40px rgba(0,0,0,.13);text-align:center}.document-header{min-height:88px;display:flex;align-items:center;justify-content:center;gap:18px}.document-logo{display:block;max-width:105px;max-height:82px;object-fit:contain}.header-copy{text-align:center}.org{font:700 15px Arial;text-transform:uppercase;letter-spacing:.08em;color:var(--jp-accent)}h1{margin:24px 0 5px;color:var(--jp-accent);font:700 36px Arial;letter-spacing:.04em}.number{font:13px Arial;color:#64736f}.lead{margin-top:42px}.name{margin:20px auto 9px;font-size:27px;font-weight:bold}.title{max-width:650px;margin:12px auto;font-style:italic}.body{max-width:650px;margin:26px auto}.meta{margin:28px auto;padding:18px;border-top:1px solid #dce5e2;border-bottom:1px solid #dce5e2;text-align:left}.closing{display:flex;align-items:flex-end;justify-content:space-between;gap:35px;margin-top:38px}.qr-box{width:126px;color:#64736f;font:10px/1.35 Arial;text-align:center}.qr-code{width:112px;height:112px;margin:0 auto 7px}.qr-code svg{display:block;width:100%;height:100%}.sign{width:300px;margin:0 0 0 auto}.sign span{font:13px Arial}.sign-assets{height:125px;position:relative;margin:4px auto -5px}.signature-image{position:absolute;z-index:2;left:50%;top:10px;transform:translateX(-50%) scale(1.35);transform-origin:center center;max-width:185px;max-height:82px;object-fit:contain}.stamp-image{position:absolute;z-index:1;left:54px;top:5px;max-width:105px;max-height:100px;object-fit:contain;opacity:.9}.sign strong{display:block;border-bottom:1px solid #333}.sign.no-assets strong{margin-top:55px}.verify{margin-top:25px;color:#64736f;font:11px Arial}.verify a{color:inherit;overflow-wrap:anywhere}@media print{body{background:#fff}.actions{display:none}.sheet{margin:0;box-shadow:none}}@media(max-width:820px){.sheet{width:auto;min-height:0;margin:0;padding:35px 24px;border-width:6px}.document-header{flex-direction:column}.closing{align-items:center;flex-direction:column-reverse}.sign{margin:0 auto}.qr-box{margin:auto}}body.jp-preview-fit{width:100vw;height:100vh;min-height:0;overflow:hidden}body.jp-preview-fit .actions{display:none}body.jp-preview-fit .sheet{position:absolute;left:50%;top:50%;width:210mm!important;min-height:297mm!important;max-width:none!important;margin:0!important;transform:translate(-50%,-50%) scale(var(--jp-fit-scale,1));transform-origin:center center}
		{/literal}
	</style>
</head>
<body{if $fitPreview} class="jp-preview-fit"{/if}>
	<div class="actions"><button onclick="window.print()">Cetak / Simpan PDF</button></div>
	<main class="sheet">
		<header class="document-header">{if $documentLogo}<img class="document-logo" src="{$documentLogo|escape}" alt="Logo jurnal">{/if}<div class="header-copy"><div class="org">{$organizationName|escape}</div><div>{$journalName|escape}</div></div></header>
		<h1>{$documentHeading|escape}</h1><div class="number">Nomor: {$documentNumber|escape}</div><p class="lead">{$documentLead|escape}</p><div class="name">{$record->payer_name|escape}</div><div class="body">{$documentText|escape|nl2br}</div>
		<div class="meta"><strong>Judul Artikel</strong><div class="title">{$record->article_title|escape}</div><strong>ID Artikel:</strong> {$record->article_id|escape}<br>{if $issueLabel}<strong>{$issueLabelTitle|escape}:</strong> {$issueLabel|escape}<br>{/if}<strong>{$publicationDateLabel|escape}:</strong> {$publicationDate|jp_date:"d-m-Y"}</div>
		<div class="closing"><div class="qr-box"><div id="jp-document-qr" class="qr-code" data-jp-qr="{$verificationUrl|escape}"></div><span>Pindai untuk memverifikasi dokumen</span></div><div class="sign{if !$signatureImage && !$stampImage} no-assets{/if}"><span>{$documentDateLabel|escape} pada {$issuedAt|jp_date:"d-m-Y"}</span>{if $signatureImage || $stampImage}<div class="sign-assets">{if $stampImage}<img class="stamp-image" src="{$stampImage|escape}" alt="Stempel">{/if}{if $signatureImage}<img class="signature-image" src="{$signatureImage|escape}" alt="Tanda tangan">{/if}</div>{/if}<strong>{$signerName|escape}</strong><span>{$signerTitle|escape}</span></div></div>
		<div class="verify">Dokumen diterbitkan melalui sistem jurnal.<br><a href="{$verificationUrl|escape}">{$verificationUrl|escape}</a></div>
	</main>
	<script src="{$qrScriptUrl|escape}"></script>
	{if $fitPreview}<script>{literal}(function(){function fit(){var sheet=document.querySelector('.sheet');if(!sheet)return;var gap=24;var scale=Math.min((window.innerWidth-gap)/sheet.offsetWidth,(window.innerHeight-gap)/sheet.offsetHeight,1);document.documentElement.style.setProperty('--jp-fit-scale',Math.max(scale,.1));}window.addEventListener('load',fit);window.addEventListener('resize',fit);setTimeout(fit,0);setTimeout(fit,150);})();{/literal}</script>{/if}
</body>
</html>
