{if !$journalPaymentResultsOnly}
{if !$journalPaymentEmbedded}{include file="frontend/components/header.tpl" pageTitleTranslated=$pageTitleTranslated}{/if}
<style>:root {ldelim} --jp-accent: {$jpAccentColor|escape}; {rdelim}</style>
<main class="jp-page jp-admin{if $journalPaymentEmbedded} jp-embedded{/if}{if $isProductionEditorOnly} jp-production-editor-only{/if}" data-theme-mode="{$jpThemeMode|escape}">
	<div class="jp-admin-head"><div><h1>{if $isProductionEditorOnly}Production Editor{elseif $isFullPaymentManager}Manajemen Pembayaran{else}Pembayaran Ditugaskan{/if}</h1><span class="jp-version-badge" title="Versi plugin Journal Payment yang terpasang">Journal Payment v{$journalPaymentVersion|escape}</span></div><div class="jp-admin-head-actions" role="toolbar" aria-label="Tautan halaman pembayaran"><a class="jp-icon-button jp-icon-secondary jp-top-icon" target="_blank" rel="noopener" href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="documents"}" data-tooltip="Cari LOA dan sertifikat" title="Cari LOA dan sertifikat" aria-label="Cari LOA dan sertifikat"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 2h10l4 4v7"></path><path d="M14 2v5h5"></path><path d="M5 2v20h8"></path><circle cx="17" cy="17" r="3"></circle><path d="m19.2 19.2 2.3 2.3"></path></svg></a><a class="jp-icon-button jp-icon-secondary jp-top-icon" {if $journalPaymentEmbedded}target="_blank" rel="noopener"{/if} href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="submit"}" data-tooltip="Lihat halaman publik" title="Lihat halaman publik" aria-label="Lihat halaman pembayaran publik"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M3 12h18M12 3a15 15 0 0 1 0 18M12 3a15 15 0 0 0 0 18"></path><path d="m16 8 3 3-3 3"></path></svg></a></div></div>
	{if $recordResult == 'updated'}<div class="jp-alert jp-alert-success" role="status"><strong>Data berhasil diperbarui.</strong></div>{elseif $recordResult == 'deleted'}<div class="jp-alert jp-alert-success" role="status"><strong>Data pembayaran dan bukti terkait berhasil dihapus.</strong></div>{elseif $recordResult == 'invalid'}<div class="jp-alert jp-alert-error" role="alert"><strong>Data belum dapat disimpan.</strong> Nama, email, WhatsApp, judul, tanggal terbit, serta data volume/nomor/tahun harus valid.</div>{elseif $recordResult == 'notFound'}<div class="jp-alert jp-alert-error" role="alert"><strong>Data pembayaran tidak ditemukan.</strong></div>{elseif $recordResult == 'financeLocked'}<div class="jp-alert jp-alert-error" role="alert"><strong>Transaksi sudah masuk laporan keuangan.</strong> Status dan data pembayaran tidak dapat dihapus agar riwayat setoran tetap utuh.</div>{/if}
	{if $documentMail == 'loaSent'}<div class="jp-alert jp-alert-success" role="status"><strong>Email LOA berhasil dikirim.</strong> Tautan dokumen telah dikirim melalui email penulis.</div>{elseif $documentMail == 'certificateSent'}<div class="jp-alert jp-alert-success" role="status"><strong>Email sertifikat berhasil dikirim.</strong> Tautan dokumen telah dikirim melalui email penulis.</div>{elseif $documentMail == 'invalidEmail'}<div class="jp-alert jp-alert-error" role="alert"><strong>Email tidak valid.</strong> Periksa alamat email penulis pada data submission.</div>{elseif $documentMail == 'unavailable'}<div class="jp-alert jp-alert-error" role="alert"><strong>Dokumen belum dapat dikirim.</strong> Pastikan pembayaran terverifikasi dan dokumen sudah diterbitkan.</div>{elseif $documentMail == 'sendFailed'}<div class="jp-alert jp-alert-error" role="alert"><strong>Email gagal dikirim.</strong> Periksa konfigurasi SMTP dan log email OJS.</div>{/if}
	{if $proofResult == 'uploaded'}<div class="jp-alert jp-alert-success" role="status"><strong>Galley akhir berhasil diunggah.</strong> Tautan proofreading telah dikirim kepada penulis melalui email.</div>{elseif $proofResult == 'uploadedEmailFailed'}<div class="jp-alert jp-alert-warning" role="status"><strong>Galley berhasil diunggah, tetapi email gagal dikirim.</strong> Kirim ulang email atau bagikan tautan melalui WhatsApp.</div>{elseif $proofResult == 'emailSent'}<div class="jp-alert jp-alert-success" role="status"><strong>Tautan proofreading berhasil dikirim ulang.</strong></div>{elseif $proofResult == 'emailFailed'}<div class="jp-alert jp-alert-error" role="alert"><strong>Email proofreading gagal dikirim.</strong> Periksa konfigurasi email OJS.</div>{elseif $proofResult == 'invalidFile'}<div class="jp-alert jp-alert-error" role="alert"><strong>Galley tidak valid.</strong> Unggah satu file PDF sesuai batas ukuran plugin.</div>{elseif $proofResult == 'published'}<div class="jp-alert jp-alert-warning" role="alert"><strong>Artikel sudah dipublikasikan.</strong> Galley proofreading baru tidak dapat ditambahkan setelah publikasi.</div>{elseif $proofResult == 'unavailable'}<div class="jp-alert jp-alert-error" role="alert"><strong>Proofreading belum tersedia.</strong> Pembayaran harus terverifikasi dan submission harus berada dalam penugasan Anda.</div>{elseif $proofResult == 'failed' or $proofResult == 'invalid'}<div class="jp-alert jp-alert-error" role="alert"><strong>Galley belum dapat diproses.</strong> Silakan periksa data dan coba kembali.</div>{/if}
	{if !$isProductionEditorOnly}<div class="jp-package-stats">{foreach from=$packageStats item=packageStat}<section class="jp-package-stat"><span>{$packageStat.name|escape}</span><strong>Rp {$packageStat.verified_total|number_format:0:',':'.'}</strong><small>{$packageStat.submission_count} transaksi · {$packageStat.verified_count} pembayaran diterima</small></section>{/foreach}</div>{/if}
	{if $view == 'production'}<style>.jp-filter{ldelim}display:none!important{rdelim}</style>{/if}
	<nav class="jp-manage-tabs" aria-label="Kelompok data pembayaran"><a class="{if $view == 'active'}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=active#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="active"}{/if}" data-payment-view="active">Aktif <span>{$activeCount}</span></a><a class="{if $view == 'archive'}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=archive#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="archive"}{/if}" data-payment-view="archive">Arsip <span>{$archiveCount}</span></a>{if $canManagePaymentRecords}<a class="jp-finance-tab {if $view == 'finance'}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=finance#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="finance"}{/if}" data-payment-view="finance"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18v14H3z"></path><path d="M7 6V4h10v2M7 13h4M16 11v4M14 13h4"></path></svg>Keuangan</a>{/if}{if $isFullPaymentManager or $isProductionEditor}<a class="{if $view == 'production'}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=production#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="production"}{/if}" data-payment-view="production">Production Editor</a>{/if}{if $isFullPaymentManager}<a class="jp-drive-tab {if $view == 'drive'}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=drive#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="drive"}{/if}" data-payment-view="drive"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h7l2 2h9v11H3z"></path></svg>Folder GD</a><a class="jp-audit-tab {if $view == 'audit'}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=audit#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="audit"}{/if}" data-payment-view="audit">Audit</a>{/if}</nav>
	<form class="jp-filter" {if $view == 'drive' or $view == 'finance' or $view == 'audit'}hidden{/if} method="get" action="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}{/if}"{if $journalPaymentEmbedded} data-fetch-url="{$journalPaymentFetchUrl|escape}"{/if}><input type="hidden" name="view" value="{$view|escape}"><input type="hidden" name="driveFolder" value="{$driveSelectedFolder|escape}"><input name="q" value="{$q|escape}" placeholder="Cari kode, ID artikel, nama, atau email"><select name="filter"><option value="">Semua Status Artikel</option>{foreach from=$editorialStatusOptions key=statusKey item=statusOption}<option value="{$statusKey|escape}" data-payment-scope="{$statusOption.scope|escape}" {if $statusOption.scope != $view}disabled hidden{/if} {if $filter == $statusKey}selected{/if}>{$statusOption.label|escape}</option>{/foreach}</select><select name="urgency"><option value="">Semua Prioritas</option>{foreach from=$urgencyOptions key=urgencyKey item=urgencyLabel}<option value="{$urgencyKey|escape}" {if $urgency == $urgencyKey}selected{/if}>{$urgencyLabel|escape}</option>{/foreach}</select><button class="jp-button" type="submit">Cari</button></form>
{/if}

	<div id="jp-payment-results" class="jp-payment-results" aria-live="polite">
	{if $view == 'finance'}
		<section class="jp-finance" aria-label="Laporan keuangan per nomor terbitan">
			{if $financeResult == 'submitted'}<div class="jp-alert jp-alert-success"><strong>Setoran berhasil dikirim.</strong> Bukti menunggu verifikasi administrator.</div>{elseif $financeResult == 'verified'}<div class="jp-alert jp-alert-success"><strong>Setoran telah diverifikasi.</strong></div>{elseif $financeResult == 'rejected'}<div class="jp-alert jp-alert-success"><strong>Setoran dikembalikan untuk diperbaiki.</strong></div>{elseif $financeResult == 'invalidFile'}<div class="jp-alert jp-alert-error"><strong>Bukti setoran tidak valid.</strong> Gunakan PDF, JPG, PNG, atau WebP sesuai batas unggahan.</div>{elseif $financeResult == 'invalid' or $financeResult == 'invalidDecision'}<div class="jp-alert jp-alert-error"><strong>Data setoran tidak valid.</strong> Periksa nominal, bukti, dan catatan keputusan.</div>{elseif $financeResult == 'failed'}<div class="jp-alert jp-alert-error"><strong>Bukti setoran belum dapat disimpan.</strong></div>{/if}
			<div class="jp-finance-summary"><div><span>Artikel Published</span><strong>{$financeTotals.articles|escape}</strong></div><div><span>Pendapatan Bruto</span><strong>Rp {$financeTotals.gross|number_format:0:',':'.'}</strong></div><div><span>Fee Editor</span><strong>Rp {$financeTotals.editor_share|number_format:0:',':'.'}</strong></div><div><span>Hak Administrator</span><strong>Rp {$financeTotals.admin_share|number_format:0:',':'.'}</strong></div><div><span>Setoran Diverifikasi</span><strong>Rp {$financeTotals.verified|number_format:0:',':'.'}</strong></div><div><span>Sisa Setoran</span><strong>Rp {$financeTotals.outstanding|number_format:0:',':'.'}</strong></div></div>
			<p class="jp-finance-note">Laporan hanya menghitung pembayaran terverifikasi dari artikel yang sudah berstatus <strong>Published</strong> di OJS. Pembagian tiap artikel dikunci saat pertama kali masuk laporan agar riwayat tidak berubah.</p>
			{if $isFullPaymentManager && $financeUnassignedCount > 0}<div class="jp-alert jp-alert-error"><strong>{$financeUnassignedCount} artikel Published belum memiliki editor keuangan.</strong> Tetapkan Section Editor pada workflow OJS, lalu muat ulang tab Keuangan.</div>{/if}
			{if $financeGroups|@count}<div class="jp-finance-groups">{foreach from=$financeGroups item=group}<article class="jp-finance-group"><header><div><span>Nomor Terbitan</span><h2>{$group.issue_label|escape}</h2><small>{$group.editor_name|escape} · {$group.articles} artikel</small></div><span class="jp-finance-balance {if $group.outstanding > 0}is-due{else}is-paid{/if}">{if $group.outstanding > 0}Sisa Rp {$group.outstanding|number_format:0:',':'.'}{else}Lunas{/if}</span></header><div class="jp-finance-metrics"><div><span>Bruto</span><strong>Rp {$group.gross|number_format:0:',':'.'}</strong></div><div><span>Fee editor</span><strong>Rp {$group.editor_share|number_format:0:',':'.'}</strong></div><div><span>Hak admin</span><strong>Rp {$group.admin_share|number_format:0:',':'.'}</strong></div><div><span>Menunggu verifikasi</span><strong>Rp {$group.pending|number_format:0:',':'.'}</strong></div></div><details class="jp-finance-articles"><summary>Rincian artikel</summary><table><thead><tr><th>ID</th><th>Judul</th><th>Pembayaran</th><th>Hak Admin</th></tr></thead><tbody>{foreach from=$group.article_rows item=article}<tr><td>{$article.article_id|escape}</td><td>{$article.title|escape}</td><td>Rp {$article.amount|number_format:0:',':'.'}</td><td>Rp {$article.admin_share|number_format:0:',':'.'}</td></tr>{/foreach}</tbody></table></details>{if $group.can_upload && $group.available_to_remit > 0}<details class="jp-remittance-upload"><summary>Unggah setoran administrator</summary><form method="post" enctype="multipart/form-data" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="financeAction" value="uploadRemittance"><input type="hidden" name="issueKey" value="{$group.issue_key|escape}"><label><span>Nominal setoran (maksimal Rp {$group.available_to_remit|number_format:0:',':'.'})</span><input name="remittanceAmount" type="number" min="1" max="{$group.available_to_remit|escape}" value="{$group.available_to_remit|escape}" required></label><label><span>Bukti transfer</span><input name="remittanceProof" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required></label><label class="jp-remittance-wide"><span>Catatan (opsional)</span><input name="remittanceNotes" maxlength="5000" placeholder="Contoh: setoran tahap 1"></label><button class="jp-button" type="submit">Kirim Setoran</button></form></details>{/if}</article>{/foreach}</div>{else}<div class="jp-card jp-empty">Belum ada pembayaran terverifikasi dari artikel Published yang dapat dimasukkan ke laporan keuangan.</div>{/if}
			<h2 class="jp-finance-history-title">Riwayat Setoran</h2>{if $financeRemittances|@count}<div class="jp-list-wrap"><table class="jp-remittance-table"><thead><tr><th>Tanggal</th><th>Terbitan / Editor</th><th>Nominal</th><th>Bukti</th><th>Status</th>{if $isFullPaymentManager}<th>Keputusan</th>{/if}</tr></thead><tbody>{foreach from=$financeRemittances item=remittance}<tr><td>{$remittance.created_at|jp_date:"d-m-Y H:i"}</td><td><strong>{$remittance.issue_label|escape}</strong><small>{$remittance.editor_name|escape}</small></td><td><strong>Rp {$remittance.amount|number_format:0:',':'.'}</strong>{if $remittance.editor_notes}<small>{$remittance.editor_notes|escape}</small>{/if}</td><td><a class="jp-icon-button jp-icon-secondary jp-document-preview" href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="remittanceProof" id=$remittance.remittance_id}" data-preview-name="Bukti Setoran — {$remittance.editor_name|escape}" data-tooltip="Lihat bukti setoran" title="Lihat bukti setoran" aria-label="Lihat bukti setoran"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"></path><circle cx="12" cy="12" r="3"></circle></svg></a></td><td><span class="jp-remittance-status jp-remittance-{$remittance.status|escape}">{if $remittance.status == 'verified'}Diverifikasi{elseif $remittance.status == 'rejected'}Perlu Perbaikan{else}Menunggu{/if}</span>{if $remittance.manager_notes}<small>{$remittance.manager_notes|escape}</small>{/if}</td>{if $isFullPaymentManager}<td>{if $remittance.status == 'pending'}<div class="jp-remittance-actions"><form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="financeAction" value="verifyRemittance"><input type="hidden" name="remittanceId" value="{$remittance.remittance_id|escape}"><button class="jp-icon-button jp-icon-verify" type="submit" data-tooltip="Verifikasi setoran" title="Verifikasi setoran" aria-label="Verifikasi setoran"><svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"></path></svg></button></form><details><summary class="jp-icon-button jp-icon-secondary" data-tooltip="Minta perbaikan" title="Minta perbaikan"><svg viewBox="0 0 24 24"><path d="m4 4 16 16M20 4 4 20"></path></svg></summary><form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="financeAction" value="rejectRemittance"><input type="hidden" name="remittanceId" value="{$remittance.remittance_id|escape}"><input name="remittanceManagerNotes" required maxlength="5000" placeholder="Alasan perbaikan"><button class="jp-button" type="submit">Kirim</button></form></details></div>{else}—{/if}</td>{/if}</tr>{/foreach}</tbody></table></div>{else}<div class="jp-card jp-empty">Belum ada riwayat setoran.</div>{/if}
			</section>
		{elseif $view == 'production'}
			{include file=$journalPaymentProductionEditorTemplate}
		{elseif $view == 'audit'}
		<section class="jp-audit" aria-label="Audit dan keamanan pembayaran">
			<div class="jp-audit-intro"><div><span>Audit &amp; Keamanan</span><strong>Riwayat aktivitas tidak dapat diedit dari antarmuka</strong><small>Menampilkan 150 aktivitas dan 150 email terbaru. Token dokumen tidak pernah ditampilkan di log.</small></div><div><span>Proteksi aktif</span><strong>Token 256-bit · QR permanen · pembatasan pencarian</strong><small>Identitas jaringan disimpan dalam bentuk hash, bukan alamat IP mentah.</small></div></div>
			<h2>Riwayat Perubahan</h2>
			{if $auditLogs|@count}<div class="jp-list-wrap"><table class="jp-audit-table"><thead><tr><th>Waktu / Pengguna</th><th>Aktivitas</th><th>Artikel</th><th>Nilai Lama</th><th>Nilai Baru</th></tr></thead><tbody>{foreach from=$auditLogs item=log}<tr><td><strong>{$log->created_at|jp_date:"d-m-Y H:i:s"}</strong><small>{$log->actor_name|escape}</small></td><td><strong>{$log->action_label|escape}</strong>{if $log->notes}<small>{$log->notes|escape}</small>{/if}</td><td>{if $log->article_id}{$log->article_id|escape}{else}—{/if}</td><td><small>{$log->old_display|escape|default:'—'}</small></td><td><small>{$log->new_display|escape|default:'—'}</small></td></tr>{/foreach}</tbody></table></div>{else}<div class="jp-card jp-empty">Belum ada aktivitas sejak fitur audit diaktifkan.</div>{/if}
			<h2>Riwayat Pengiriman Email</h2>
			{if $emailLogs|@count}<div class="jp-list-wrap"><table class="jp-audit-table"><thead><tr><th>Waktu</th><th>Jenis / Artikel</th><th>Penerima</th><th>Subjek</th><th>Status</th></tr></thead><tbody>{foreach from=$emailLogs item=mail}<tr><td>{$mail->created_at|jp_date:"d-m-Y H:i:s"}</td><td><strong>{$mail->email_type|replace:'_':' '|capitalize|escape}</strong><small>{if $mail->article_id}ID {$mail->article_id|escape}{else}—{/if}</small></td><td>{$mail->recipient|escape}</td><td>{$mail->subject|escape}</td><td><span class="jp-email-state jp-email-{$mail->status|escape}">{if $mail->status == 'sent'}Terkirim{else}Gagal{/if}</span>{if $mail->error_message}<small>{$mail->error_message|escape}</small>{/if}</td></tr>{/foreach}</tbody></table></div>{else}<div class="jp-card jp-empty">Belum ada riwayat email sejak fitur audit diaktifkan.</div>{/if}
		</section>
	{elseif $view == 'drive'}
		<section class="jp-drive-manager" data-drive-folder="{$driveSelectedFolder|escape}" aria-label="Pengelola file Google Drive">
			{if $driveResult == 'folderCreated'}<div class="jp-alert jp-alert-success" role="status"><strong>Folder berhasil dibuat di Google Drive.</strong></div>{elseif $driveResult == 'uploaded'}<div class="jp-alert jp-alert-success" role="status"><strong>File berhasil diunggah dan tersinkron ke Google Drive.</strong></div>{elseif $driveResult == 'renamed'}<div class="jp-alert jp-alert-success" role="status"><strong>Nama file berhasil diperbarui.</strong></div>{elseif $driveResult == 'trashed'}<div class="jp-alert jp-alert-success" role="status"><strong>File dipindahkan ke Sampah Google Drive.</strong> File masih dapat dipulihkan dari Drive.</div>{elseif $driveResult == 'notConfigured'}<div class="jp-alert jp-alert-error" role="alert"><strong>Google Drive belum dikonfigurasi.</strong></div>{elseif $driveResult == 'invalidFolder' or $driveResult == 'invalid'}<div class="jp-alert jp-alert-error" role="alert"><strong>Data folder atau file tidak valid.</strong></div>{elseif $driveResult == 'failed'}<div class="jp-alert jp-alert-error" role="alert"><strong>Operasi Google Drive gagal.</strong> Periksa koneksi dan log PHP.</div>{/if}
			{if $driveError == 'root'}<div class="jp-card jp-empty"><strong>Folder induk belum tersedia.</strong><br>Isi tautan folder Google Drive pada Pengaturan plugin.</div>
			{elseif $driveError == 'credentials'}<div class="jp-card jp-empty"><strong>OAuth Google Drive belum tersedia.</strong><br>Isi Client ID, Client Secret, dan Refresh Token pada Pengaturan plugin.</div>
			{elseif $driveError == 'connection'}<div class="jp-card jp-empty"><strong>Google Drive belum dapat dibaca.</strong><br>Periksa OAuth, izin folder, koneksi cURL, dan log PHP.</div>
			{else}
				<div class="jp-drive-summary">
					<div><span>Folder aktif</span><strong>{$driveSelectedFolderName|escape}</strong><small>{$driveFiles|@count} file publikasi</small></div>
					<div><span>Halaman terakhir</span><strong>{if $driveLastPage ne null}{$driveLastPage|escape}{else}Belum terdeteksi{/if}</strong><small>{if $driveLatestFile}{$driveLatestFile|escape}{else}Folder masih kosong{/if}</small></div>
					<div class="jp-drive-summary-actions" role="toolbar" aria-label="Tindakan Folder GD"><button class="jp-icon-button jp-icon-secondary" type="button" data-drive-refresh data-tooltip="Segarkan data Folder GD" title="Segarkan data Folder GD" aria-label="Segarkan data Folder GD"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6v5h-5"></path><path d="M4 18v-5h5"></path><path d="M6.1 9a7 7 0 0 1 11.4-2.4L20 9"></path><path d="M17.9 15a7 7 0 0 1-11.4 2.4L4 15"></path></svg></button><a class="jp-icon-button jp-icon-secondary" href="{$driveSelectedFolderUrl|escape}" target="_blank" rel="noopener" data-tooltip="Buka folder di Google Drive" title="Buka folder di Google Drive" aria-label="Buka folder di Google Drive"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h7l2 2h9v11H3z"></path><path d="m14 12 4-4m-3 0h3v3"></path></svg></a></div>
				</div>
				<div class="jp-drive-toolbar">
					<form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="driveAction" value="createFolder"><input type="hidden" name="driveFolder" value="{$driveSelectedFolder|escape}"><input name="folderName" required maxlength="150" placeholder="Contoh: Volume 7 Nomor 3"><button class="jp-button" type="submit">Buat Folder</button></form>
					<form method="post" enctype="multipart/form-data" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="driveAction" value="upload"><input type="hidden" name="driveFolder" value="{$driveSelectedFolder|escape}"><input type="file" name="driveFile" required accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip,.epub,.jpg,.jpeg,.png,.webp,.txt"><button class="jp-button" type="submit">Unggah File</button></form>
				</div>
				<div class="jp-drive-browser">
					<nav class="jp-drive-folders" aria-label="Folder Google Drive"><h2>Folder Terbitan</h2>{foreach from=$driveFolders item=folder}<a class="{if $folder.id == $driveSelectedFolder}is-active{/if}" href="{if $journalPaymentEmbedded}{$journalPaymentSettingsUrl|escape}?view=drive&amp;driveFolder={$folder.id|escape}#journalPayment{else}{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" view="drive" driveFolder=$folder.id}{/if}" data-drive-folder-id="{$folder.id|escape}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h7l2 2h9v11H3z"></path></svg><span>{$folder.name|escape}</span>{if $folder.is_root}<small>Induk</small>{/if}</a>{/foreach}</nav>
					<div class="jp-drive-files"><h2>File — {$driveSelectedFolderName|escape}</h2>{if $driveFiles|@count}<div class="jp-drive-file-list">{foreach from=$driveFiles item=file}<article class="jp-drive-file"><a class="jp-drive-file-main" href="{$file.view_url|escape}" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 2h10l4 4v16H5z"></path><path d="M14 2v5h5"></path></svg><span><strong>{$file.name|escape}</strong><small>{$file.size_label|escape} · {$file.modifiedTime|jp_date:"d-m-Y H:i"}{if $file.last_page ne null} · Halaman {$file.last_page|escape}{/if}</small></span></a><div class="jp-drive-file-actions"><details><summary class="jp-icon-button jp-icon-secondary" data-tooltip="Ubah nama" title="Ubah nama" aria-label="Ubah nama"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20h9"></path><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4z"></path></svg></summary><form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="driveAction" value="rename"><input type="hidden" name="driveFolder" value="{$driveSelectedFolder|escape}"><input type="hidden" name="driveFileId" value="{$file.id|escape}"><input name="driveFileName" value="{$file.name|escape}" required maxlength="220"><button class="jp-button" type="submit">Simpan</button></form></details><form class="jp-drive-trash-form" method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}" data-drive-file-name="{$file.name|escape}">{csrf}<input type="hidden" name="driveAction" value="trash"><input type="hidden" name="driveFolder" value="{$driveSelectedFolder|escape}"><input type="hidden" name="driveFileId" value="{$file.id|escape}"><button class="jp-icon-button jp-icon-secondary" type="submit" data-tooltip="Pindahkan ke Sampah" title="Pindahkan ke Sampah" aria-label="Pindahkan file ke Sampah"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v5M14 11v5"></path></svg></button></form></div></article>{/foreach}</div>{else}<div class="jp-card jp-empty">Folder ini belum berisi file.</div>{/if}</div>
				</div>
			{/if}
		</section>
	{elseif $records|@count}
		<div class="jp-list-wrap">
			<table class="jp-payment-list">
				<thead><tr><th>Nama / Artikel</th><th>ID Artikel</th><th>Paket</th><th>Jumlah</th><th>Status Artikel</th><th>Tanggal Publikasi</th></tr></thead>
				<tbody>
				{foreach from=$records item=record}
					<tr class="jp-list-row" tabindex="0" role="button" aria-expanded="false" aria-controls="jp-detail-{$record->payment_id|escape}" data-detail-id="jp-detail-{$record->payment_id|escape}" title="Klik untuk melihat detail pembayaran">
						<td><strong class="jp-list-name">{$record->payer_name|escape}</strong>{if $record->article_title}<span class="jp-list-title" title="{$record->article_title|escape}">{$record->article_title|escape}</span>{/if}<span class="jp-list-code">{$record->tracking_code|escape}</span><a class="jp-list-editor" target="_blank" rel="noopener" href="{$record->workflow_url|escape}" title="Buka workflow dan kelola penugasan editor di OJS">Editor: {$record->assigned_editor_label|escape}</a></td>
						<td class="jp-list-id">{$record->article_id|escape}</td>
						<td>{$record->package_name|escape}</td>
						<td class="jp-list-amount">Rp {$record->amount|number_format:0:',':'.'}</td>
						<td><span class="jp-editorial-label jp-editorial-{$record->editorial_status_key|escape}">{$record->editorial_status_label|escape}</span></td>
						<td class="jp-list-date"><strong class="jp-list-publish">{$record->publication_date|jp_date:"d-m-Y"}</strong><span class="jp-urgency jp-urgency-{$record->urgency_key|escape}" title="{$record->urgency_note|escape}">{$record->urgency_label|escape}</span>{if $record->action_due_date}<span class="jp-list-deadline">Tenggat: {$record->action_due_date|jp_date:"d-m-Y"}</span>{/if}</td>
					</tr>
					<tr id="jp-detail-{$record->payment_id|escape}" class="jp-list-detail" hidden>
						<td colspan="6">
							<section class="jp-record-detail" aria-label="Detail pembayaran ID Artikel {$record->article_id|escape}">
								<button class="jp-detail-close" type="button" data-detail-id="jp-detail-{$record->payment_id|escape}" aria-label="Tutup detail" title="Tutup detail">×</button>
								{if $canManagePaymentRecords}<div class="jp-compact-actions jp-icon-toolbar" role="toolbar" aria-label="Tindakan submission dan dokumen">
									<button class="jp-icon-button jp-icon-secondary jp-document-preview" type="button" data-preview-url="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="proof" id=$record->payment_id}" data-preview-name="Bukti Pembayaran — {$record->proof_name|escape}" data-tooltip="Lihat bukti pembayaran" title="Lihat bukti pembayaran" aria-label="Lihat bukti pembayaran"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"></path><circle cx="12" cy="12" r="3"></circle></svg></button>
									{if $record->wa_link}<a class="jp-icon-button jp-icon-whatsapp" target="_blank" rel="noopener" href="{$record->wa_link|escape}" data-tooltip="Hubungi melalui WhatsApp" title="Hubungi melalui WhatsApp" aria-label="Hubungi pembayar melalui WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.4 9.4 0 0 1-3.8-.9L3 21l1.8-5.1A8.5 8.5 0 1 1 21 11.5z"></path><path d="M8.2 7.8c.3-.5.6-.5.9-.5h.4c.2 0 .4.1.5.4l.8 2c.1.3.1.5-.1.7l-.6.8c-.2.2-.1.4 0 .6.8 1.4 2 2.5 3.5 3.2.3.1.5.1.7-.1l.9-1.1c.2-.2.4-.3.7-.2l2 .9c.3.1.4.3.4.5 0 .5-.3 1.5-.8 2-.6.6-1.5.9-2.4.7-1.3-.3-3.2-1-5.1-2.7-1.5-1.3-2.7-3-3.2-4.4-.5-1.2 0-2.2.4-2.8z"></path></svg></a>{/if}
									<form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="paymentId" value="{$record->payment_id|escape}"><button class="jp-icon-button jp-icon-verify" name="newStatus" value="verified" type="submit" data-tooltip="Verifikasi pembayaran" title="Verifikasi pembayaran" aria-label="Verifikasi pembayaran"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 6 9 17l-5-5"></path></svg></button></form>
									<button class="jp-icon-button jp-icon-edit jp-edit-toggle" type="button" aria-expanded="false" aria-controls="jp-edit-{$record->payment_id|escape}" data-edit-id="jp-edit-{$record->payment_id|escape}" data-tooltip="Edit data pembayaran" title="Edit data pembayaran" aria-label="Edit data pembayaran"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20h9"></path><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4z"></path></svg></button>
									<form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}" data-delete-record="true" data-article-id="{$record->article_id|escape}">{csrf}<input type="hidden" name="paymentId" value="{$record->payment_id|escape}"><button class="jp-icon-button jp-icon-delete" name="recordAction" value="delete" type="submit" data-tooltip="Hapus pembayaran" title="Hapus pembayaran" aria-label="Hapus pembayaran"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18"></path><path d="M8 6V4h8v2"></path><path d="M19 6l-1 15H6L5 6"></path><path d="M10 11v5M14 11v5"></path></svg></button></form>
									{if $record->status == 'verified'}<form class="jp-document-icon-form" method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="paymentId" value="{$record->payment_id|escape}">
										<a class="jp-icon-button jp-icon-secondary jp-document-preview" href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="receipt" articleId=$record->article_id access=$record->document_access_token}" data-preview-name="Kuitansi Pembayaran" data-tooltip="Lihat kuitansi" title="Lihat kuitansi" aria-label="Lihat kuitansi"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h12v20l-3-2-3 2-3-2-3 2z"></path><path d="M9 7h6M9 11h6M9 15h4"></path></svg></a>
										{if !$record->loa_issued_at}<button class="jp-icon-button jp-icon-secondary" name="documentAction" value="issueLoa" type="submit" data-tooltip="Terbitkan LOA" title="Terbitkan LOA" aria-label="Terbitkan LOA"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h9l4 4v16H6z"></path><path d="M14 2v5h5M12 11v6M9 14h6"></path></svg></button>{else}<a class="jp-icon-button jp-icon-secondary jp-document-preview" href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="loa" articleId=$record->article_id access=$record->document_access_token}" data-preview-name="Letter of Acceptance (LOA)" data-tooltip="Lihat LOA" title="Lihat LOA" aria-label="Lihat LOA"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h9l4 4v16H6z"></path><path d="M14 2v5h5M9 14l2 2 4-5"></path></svg></a>{if $record->loa_send_link}<a class="jp-icon-button jp-icon-whatsapp" target="_blank" rel="noopener" href="{$record->loa_send_link|escape}" data-tooltip="Kirim LOA via WhatsApp" title="Kirim LOA via WhatsApp" aria-label="Kirim LOA melalui WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.4 9.4 0 0 1-3.8-.9L3 21l1.8-5.1A8.5 8.5 0 1 1 21 11.5z"></path><path d="M9 12h6M13 9l3 3-3 3"></path></svg></a>{/if}<button class="jp-icon-button jp-icon-email" name="documentAction" value="sendLoaEmail" type="submit" data-email-send="LOA" data-email-recipient="{$record->payer_email|escape}" data-tooltip="Kirim LOA via email" title="Kirim LOA via email" aria-label="Kirim LOA melalui email"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5h18v14H3z"></path><path d="m3 6 9 7 9-7"></path></svg></button>{/if}
										{if $record->certificate_issued_at}<a class="jp-icon-button jp-icon-certificate jp-document-preview" href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="certificate" articleId=$record->article_id access=$record->document_access_token}" data-preview-name="Sertifikat Publikasi" data-tooltip="Lihat sertifikat publikasi" title="Lihat sertifikat publikasi" aria-label="Lihat sertifikat publikasi"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="5"></circle><path d="m8.5 12-1 10 4.5-3 4.5 3-1-10M10 8l1.4 1.4L14.5 6"></path></svg></a>{if $record->certificate_send_link}<a class="jp-icon-button jp-icon-whatsapp" target="_blank" rel="noopener" href="{$record->certificate_send_link|escape}" data-tooltip="Kirim sertifikat via WhatsApp" title="Kirim sertifikat via WhatsApp" aria-label="Kirim sertifikat melalui WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 11.5a8.4 8.4 0 0 1-9 8.5 9.4 9.4 0 0 1-3.8-.9L3 21l1.8-5.1A8.5 8.5 0 1 1 21 11.5z"></path><path d="M9 12h6M13 9l3 3-3 3"></path></svg></a>{/if}<button class="jp-icon-button jp-icon-email" name="documentAction" value="sendCertificateEmail" type="submit" data-email-send="Sertifikat Publikasi" data-email-recipient="{$record->payer_email|escape}" data-tooltip="Kirim sertifikat via email" title="Kirim sertifikat via email" aria-label="Kirim sertifikat melalui email"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 5h18v14H3z"></path><path d="m3 6 9 7 9-7"></path></svg></button>{elseif $record->is_published}<button class="jp-icon-button jp-icon-certificate" name="documentAction" value="issueCertificate" type="submit" data-tooltip="Terbitkan sertifikat publikasi" title="Terbitkan sertifikat publikasi" aria-label="Terbitkan sertifikat publikasi"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="5"></circle><path d="m8.5 12-1 10 4.5-3 4.5 3-1-10M12 5v6M9 8h6"></path></svg></button>{/if}
									</form>{/if}
								</div>{/if}
								{if $record->payer_notes}<p class="jp-note">{$record->payer_notes|escape|nl2br}</p>{/if}
								{if $record->status == 'verified'}
								<details class="jp-proofreading-manager" {if $record->proofreading && $record->proofreading->status == 'corrections_requested'}open{/if}>
									<summary><strong>Proofreading Penulis</strong><span class="jp-proof-state jp-proof-{if $record->proofreading}{$record->proofreading->status|escape}{else}not_uploaded{/if}">{$record->proofreading_status_label|escape}</span></summary>
									<div class="jp-proofreading-manager-body">
										{if $record->proofreading}<div class="jp-proof-meta"><span>Versi {$record->proofreading->version_number|escape}</span><span>Diunggah {$record->proofreading->uploaded_at|jp_date:"d-m-Y H:i"}</span>{if $record->proofreading->responded_at}<span>Direspons {$record->proofreading->responded_at|jp_date:"d-m-Y H:i"}</span>{/if}</div>{if $record->proofreading->author_notes}<div class="jp-proof-note"><strong>Catatan penulis</strong><p>{$record->proofreading->author_notes|escape|nl2br}</p></div>{/if}<div class="jp-proof-actions"><a class="jp-button jp-button-secondary jp-document-preview" href="{$record->proofreading_file_url|escape}" data-preview-name="Galley Akhir — Versi {$record->proofreading->version_number|escape}">Pratinjau PDF</a><form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="paymentId" value="{$record->payment_id|escape}"><button class="jp-button jp-button-secondary" name="proofreadingAction" value="sendEmail" type="submit" data-email-send="tautan proofreading" data-email-recipient="{$record->payer_email|escape}">Kirim Ulang Email</button></form>{if $record->proofreading_wa_link}<a class="jp-button jp-button-secondary" target="_blank" rel="noopener" href="{$record->proofreading_wa_link|escape}">Kirim via WhatsApp</a>{/if}</div>{/if}
										{if !$record->is_published}<form class="jp-proof-upload" method="post" enctype="multipart/form-data" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="paymentId" value="{$record->payment_id|escape}"><input type="hidden" name="proofreadingAction" value="upload"><label><span>{if $record->proofreading}Unggah versi galley baru{else}Unggah galley akhir{/if}</span><input type="file" name="proofreadingFile" accept="application/pdf,.pdf" required></label><label><span>Catatan untuk penulis</span><textarea name="proofreadingNotes" rows="2" maxlength="10000" placeholder="Contoh: Mohon periksa nama, afiliasi, tabel, gambar, dan daftar pustaka."></textarea></label><button class="jp-button" type="submit">Unggah dan Kirim ke Penulis</button></form>{/if}
									</div>
								</details>
								{/if}
								{if $record->status == 'verified' && !$record->certificate_issued_at && !$record->is_published}<span class="jp-doc-note">Sertifikat tersedia setelah artikel dipublikasikan.</span>{/if}
								<form id="jp-edit-{$record->payment_id|escape}" class="jp-edit-form" method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}" hidden>{csrf}<input type="hidden" name="paymentId" value="{$record->payment_id|escape}"><input type="hidden" name="recordAction" value="update"><div class="jp-edit-grid"><label><span>Nama</span><input name="payerName" value="{$record->payer_name|escape}" required maxlength="255"></label><label><span>Email</span><input name="payerEmail" type="email" value="{$record->payer_email|escape}" required maxlength="255"></label><label><span>Nomor WhatsApp</span><input name="payerPhone" value="{$record->payer_phone|escape}" required inputmode="tel" maxlength="30"></label><label><span>Prediksi/Tanggal Terbit</span><input name="publicationDate" type="date" value="{$record->publication_date|escape}" required></label><label><span>Tenggat Tindakan Penulis</span><input name="actionDueDate" type="date" value="{$record->action_due_date|escape}"></label><label><span>Volume</span><input name="issueVolume" value="{$record->issue_volume|escape}" inputmode="numeric" pattern="[0-9]+" maxlength="4" placeholder="Contoh: 9"></label><label><span>Nomor Terbitan</span><input name="issueNumber" value="{$record->issue_number|escape}" maxlength="40" placeholder="Contoh: 2"></label><label><span>Tahun Terbit</span><input name="issueYear" value="{$record->issue_year|escape}" inputmode="numeric" pattern="[0-9][0-9][0-9][0-9]" maxlength="4" placeholder="Contoh: 2026"></label><label class="jp-edit-wide"><span>Judul Artikel</span><textarea name="articleTitle" rows="2" required maxlength="5000">{$record->article_title|escape}</textarea></label><label class="jp-edit-wide"><span>Catatan Internal Pengelola</span><textarea name="managerNotes" rows="2" maxlength="5000">{$record->manager_notes|escape}</textarea></label></div><p class="jp-field-help">Tenggat revisi dibuat otomatis dari keputusan OJS, tetapi dapat disesuaikan di sini. Catatan internal tidak ditampilkan kepada penulis.</p><div class="jp-edit-buttons"><button class="jp-button" type="submit">Simpan Perubahan</button><button class="jp-button jp-button-secondary jp-edit-cancel" type="button" data-edit-id="jp-edit-{$record->payment_id|escape}">Batal</button></div></form>
							</section>
						</td>
					</tr>
				{/foreach}
				</tbody>
			</table>
		</div>
	{else}<div class="jp-card jp-empty">Belum ada data pembayaran yang sesuai.</div>{/if}
	{if $view != 'drive' && $totalPages > 1}<nav class="jp-pagination">{if $journalPaymentEmbedded}{foreach from=$pageLinks item=pageLink}<a class="{if $page == $pageLink.number}is-active{/if}" href="{$pageLink.url|escape}">{$pageLink.number}</a>{/foreach}{else}{foreach from=$pageNumbers item=pageNumber}<a class="{if $page == $pageNumber}is-active{/if}" href="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage" p=$pageNumber q=$q filter=$filter urgency=$urgency view=$view}">{$pageNumber}</a>{/foreach}{/if}</nav>{/if}
	</div>
{if !$journalPaymentResultsOnly}
</main>
{include file=$journalPaymentPreviewModalTemplate}
{if !$journalPaymentEmbedded}{include file="frontend/components/footer.tpl"}{/if}
{/if}
