<section class="jp-production" aria-label="Fee Production Editor">
	{if $productionResult == 'feeUpdated'}<div class="jp-alert jp-alert-success"><strong>Fee artikel berhasil diperbarui.</strong></div>
	{elseif $productionResult == 'paid'}<div class="jp-alert jp-alert-success"><strong>Pembayaran fee berhasil dicatat.</strong> Production Editor dapat memeriksa bukti dan mengonfirmasi penerimaan.</div>
	{elseif $productionResult == 'received'}<div class="jp-alert jp-alert-success"><strong>Penerimaan fee berhasil dikonfirmasi.</strong></div>
	{elseif $productionResult == 'invalidFile'}<div class="jp-alert jp-alert-error"><strong>Bukti transfer tidak valid.</strong> Gunakan PDF, JPG, PNG, atau WebP.</div>
	{elseif $productionResult == 'invalid'}<div class="jp-alert jp-alert-error"><strong>Data fee tidak valid.</strong> Periksa nominal, penerima, dan bukti transfer.</div>
	{elseif $productionResult == 'failed'}<div class="jp-alert jp-alert-error"><strong>Pembayaran fee belum dapat disimpan.</strong></div>{/if}

	<div class="jp-finance-summary">
		<div><span>Artikel Ditugaskan</span><strong>{$productionTotals.articles|escape}</strong></div>
		<div><span>Total Fee</span><strong>Rp {$productionTotals.fee|number_format:0:',':'.'}</strong></div>
		<div><span>Sudah Diterima</span><strong>Rp {$productionTotals.received|number_format:0:',':'.'}</strong></div>
		<div><span>Menunggu Konfirmasi</span><strong>Rp {$productionTotals.pending|number_format:0:',':'.'}</strong></div>
		<div><span>Sisa Fee</span><strong>Rp {$productionTotals.outstanding|number_format:0:',':'.'}</strong></div>
	</div>
	<p class="jp-finance-note">Hak fee dibuat otomatis dari assignment akun <strong>Production Editor</strong> pada tahap Production OJS. Tidak ada penugasan ulang di plugin dan fee ini tidak mengubah pembagian 60% editor/40% administrator.</p>

	{if $productionGroups|@count}<div class="jp-finance-groups">
	{foreach from=$productionGroups item=group}
		<article class="jp-finance-group">
			<header><div><span>Production Editor</span><h2>{$group.name|escape}</h2><small>{$group.articles} artikel ditugaskan</small></div><span class="jp-finance-balance {if $group.outstanding > 0}is-due{else}is-paid{/if}">{if $group.outstanding > 0}Sisa Rp {$group.outstanding|number_format:0:',':'.'}{else}Lunas{/if}</span></header>
			<div class="jp-finance-metrics"><div><span>Total Fee</span><strong>Rp {$group.fee|number_format:0:',':'.'}</strong></div><div><span>Sudah Diterima</span><strong>Rp {$group.received|number_format:0:',':'.'}</strong></div><div><span>Menunggu Konfirmasi</span><strong>Rp {$group.pending|number_format:0:',':'.'}</strong></div><div><span>Dapat Dibayarkan</span><strong>Rp {$group.available_to_pay|number_format:0:',':'.'}</strong></div></div>
			<details class="jp-finance-articles"><summary>Rincian artikel</summary><table><thead><tr><th>ID</th><th>Judul</th><th>Ditugaskan</th><th>Fee</th></tr></thead><tbody>
			{foreach from=$group.article_rows item=article}<tr><td>{$article.article_id|escape}</td><td>{$article.title|escape}</td><td>{$article.assigned_at|date_format:"%d-%m-%Y"}</td><td>{if $isFullPaymentManager}<form class="jp-production-fee-form" method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="productionAction" value="updateFee"><input type="hidden" name="productionFeeId" value="{$article.fee_id|escape}"><input type="number" name="productionFeeAmount" min="0" max="100000000" step="1000" value="{$article.amount|escape}" aria-label="Fee artikel {$article.article_id|escape}"><button class="jp-button jp-button-secondary" type="submit">Simpan</button></form>{else}<strong>Rp {$article.amount|number_format:0:',':'.'}</strong>{/if}</td></tr>{/foreach}
			</tbody></table></details>
			{if $isFullPaymentManager && $group.available_to_pay > 0}<details class="jp-remittance-upload"><summary>Bayar fee Production Editor</summary><form method="post" enctype="multipart/form-data" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="productionAction" value="createPayout"><input type="hidden" name="productionEditorId" value="{$group.user_id|escape}"><label><span>Nominal (maksimal Rp {$group.available_to_pay|number_format:0:',':'.'})</span><input name="productionPayoutAmount" type="number" min="1" max="{$group.available_to_pay|escape}" value="{$group.available_to_pay|escape}" required></label><label><span>Bukti transfer</span><input name="productionPayoutProof" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" required></label><label class="jp-remittance-wide"><span>Catatan (opsional)</span><input name="productionPayoutNotes" maxlength="5000" placeholder="Contoh: pembayaran fee tahap 1"></label><button class="jp-button" type="submit">Catat Pembayaran</button></form></details>{/if}
		</article>
	{/foreach}</div>{else}<div class="jp-card jp-empty">Belum ada akun Assistant yang ditugaskan sebagai Production Editor pada tahap Production submission berbayar.</div>{/if}

	<h2 class="jp-finance-history-title">Riwayat Pembayaran Fee</h2>
	{if $productionPayouts|@count}<div class="jp-list-wrap"><table class="jp-remittance-table"><thead><tr><th>Tanggal</th><th>Production Editor</th><th>Nominal</th><th>Bukti</th><th>Status</th>{if $isProductionEditorOnly}<th>Konfirmasi</th>{/if}</tr></thead><tbody>
	{foreach from=$productionPayouts item=payout}<tr><td>{$payout.created_at|date_format:"%d-%m-%Y %H:%M"}</td><td><strong>{$payout.production_editor_name|escape}</strong>{if $payout.manager_notes}<small>{$payout.manager_notes|escape}</small>{/if}</td><td><strong>Rp {$payout.amount|number_format:0:',':'.'}</strong></td><td><button class="jp-button jp-button-secondary jp-document-preview" type="button" data-preview-url="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="productionPayoutProof" id=$payout.production_payout_id}" data-preview-name="Bukti Pembayaran Fee — {$payout.production_editor_name|escape}">Lihat Bukti</button></td><td><span class="jp-remittance-status {if $payout.status == 'received'}jp-remittance-verified{else}jp-remittance-pending{/if}">{if $payout.status == 'received'}Sudah Diterima{else}Menunggu Konfirmasi{/if}</span>{if $payout.received_at}<small>{$payout.received_at|date_format:"%d-%m-%Y %H:%M"}</small>{/if}{if $payout.production_editor_notes}<small>{$payout.production_editor_notes|escape}</small>{/if}</td>{if $isProductionEditorOnly}<td>{if $payout.status == 'pending'}<form method="post" action="{url router=PKP\core\PKPApplication::ROUTE_PAGE page="journalPayment" op="manage"}">{csrf}<input type="hidden" name="productionAction" value="confirmReceived"><input type="hidden" name="productionPayoutId" value="{$payout.production_payout_id|escape}"><input name="productionEditorNotes" maxlength="5000" placeholder="Catatan opsional"><button class="jp-button" type="submit">Sudah Diterima</button></form>{else}—{/if}</td>{/if}</tr>{/foreach}
	</tbody></table></div>{else}<div class="jp-card jp-empty">Belum ada pembayaran fee Production Editor.</div>{/if}
</section>
