<!doctype html>
<html lang="id">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>{$record->receipt_no|escape}</title>
	<style>
		:root {ldelim} --jp-accent: {$accentColor|escape}; {rdelim}
		{literal}
		html,body{min-height:100%}body{margin:0;background:#eef2f1;color:#182421;font:15px/1.55 Arial,sans-serif}.qr-footer{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-top:22px}.qr-box{width:92px;text-align:center;color:#64736f;font-size:9px}.qr-code{width:80px;height:80px;margin:0 auto 4px}.qr-code svg{width:100%;height:100%;display:block}.sheet{box-sizing:border-box;width:210mm;max-width:calc(100% - 48px);min-height:148mm;margin:24px auto;padding:18mm;background:#fff;border-top:8px solid var(--jp-accent);box-shadow:0 12px 40px rgba(0,0,0,.12)}header{display:flex;justify-content:space-between;gap:30px;border-bottom:1px solid #dce5e2;padding-bottom:18px}h1{margin:4px 0;font-size:30px;color:var(--jp-accent)}.muted{color:#64736f}.status{color:#16734d;font-weight:700}.amount{font-size:28px;font-weight:700;color:var(--jp-accent)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 28px;margin:24px 0}.row{border-bottom:1px solid #edf1f0;padding:9px 0}.row span{display:block;color:#64736f;font-size:12px}.footer{margin-top:28px;border-top:1px solid #dce5e2;padding-top:14px;color:#64736f}.actions{text-align:center;margin:14px auto}.actions button{border:0;border-radius:8px;background:var(--jp-accent);color:#fff;padding:11px 18px;font-weight:bold;cursor:pointer}@media print{body{background:#fff}.sheet{width:210mm;max-width:none;margin:0;box-shadow:none}.actions{display:none}}@media(max-width:800px){.sheet{width:calc(100% - 24px);max-width:none;min-height:0;margin:12px auto;padding:24px}.grid{grid-template-columns:1fr}header{display:block}}body.jp-preview-fit{width:100vw;height:100vh;min-height:0;overflow:hidden}body.jp-preview-fit .actions{display:none}body.jp-preview-fit .sheet{position:absolute;left:50%;top:50%;width:210mm!important;min-height:148mm!important;max-width:none!important;margin:0!important;transform:translate(-50%,-50%) scale(var(--jp-fit-scale,1));transform-origin:center center}
		{/literal}
	</style>
</head>
<body{if $fitPreview} class="jp-preview-fit"{/if}>
	<div class="actions"><button onclick="window.print()">Cetak / Simpan PDF</button></div>
	<main class="sheet"><header><div><div class="muted">{$organizationName|escape}</div><h1>KUITANSI PEMBAYARAN</h1><div>{$journalName|escape}</div></div><div><div class="muted">Nomor Kuitansi</div><strong>{$record->receipt_no|escape}</strong><div class="status">LUNAS / TERVERIFIKASI</div></div></header><section class="grid"><div class="row"><span>Nama Lengkap</span><strong>{$record->payer_name|escape}</strong></div><div class="row"><span>Tanggal</span><strong>{$record->verified_at|date_format:"%d-%m-%Y"}</strong></div><div class="row"><span>ID Artikel</span><strong>{$record->article_id|escape}</strong></div><div class="row"><span>Metode Pembayaran</span><strong>{$record->payment_method|escape}</strong></div><div class="row"><span>Jenis Pembayaran</span><strong>{$record->package_name|escape}</strong></div><div class="row"><span>Kode Pelacakan</span><strong>{$record->tracking_code|escape}</strong></div></section>{if $record->article_title}<div class="row"><span>Judul Artikel</span><strong>{$record->article_title|escape}</strong></div>{/if}<p class="amount">Rp {$record->amount|number_format:0:',':'.'}</p><div class="qr-footer"><p class="footer">{$footerText|escape}</p><div class="qr-box"><div id="jp-receipt-qr" class="qr-code" data-jp-qr="{$verificationUrl|escape}"></div>Pindai untuk verifikasi</div></div></main>
	<script src="{$qrScriptUrl|escape}"></script>
	{if $fitPreview}<script>{literal}(function(){function fit(){var sheet=document.querySelector('.sheet');if(!sheet)return;var gap=24;var scale=Math.min((window.innerWidth-gap)/sheet.offsetWidth,(window.innerHeight-gap)/sheet.offsetHeight,1);document.documentElement.style.setProperty('--jp-fit-scale',Math.max(scale,.1));}window.addEventListener('load',fit);window.addEventListener('resize',fit);setTimeout(fit,0);setTimeout(fit,150);})();{/literal}</script>{/if}
</body>
</html>
